"""Added ingredients column to Meal

Revision ID: 0d7a61626938
Revises: cfd7c04eeaae
Create Date: 2025-03-04 22:10:09.561978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d7a61626938'
down_revision: Union[str, None] = 'cfd7c04eeaae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('ingredients', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meals', 'ingredients')
    # ### end Alembic commands ###
