"""Removed Like model temporarily

Revision ID: 93f28d3387a3
Revises: b6ba12d0cf21
Create Date: 2025-03-03 17:29:37.981359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93f28d3387a3'
down_revision: Union[str, None] = 'b6ba12d0cf21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
